apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask
spec:
  source:
    repoURL: https://github.com/Jishan7866/flask-app.git
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flask
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
