apiVersion: argoproj.io/v1
metadata:
  name: flask
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Jishan7866/flask-app.git
    targetRevision: HEAD
    path: ./

  destination:
    server: https://kubernetes.default.svc
    namespace: flask
  
  SyncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
